# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VM79bw8qnFD9HCjJFBsRIBIPitfQwtJt
"""


import streamlit as st
# Run this in Google Colab+
import os

# --- DB Functions ---
def get_connection():
    return sqlite3.connect("internship_tracking.db", check_same_thread=False)

def register_student(name, email):
    conn = get_connection()
    cur = conn.cursor()
    cur.execute("INSERT OR IGNORE INTO students (name, email) VALUES (?, ?)", (name, email))
    conn.commit()
    conn.close()

def log_internship(email, company, duration, feedback):
    conn = get_connection()
    cur = conn.cursor()
    cur.execute("SELECT student_id FROM students WHERE email = ?", (email,))
    result = cur.fetchone()
    if result:
        student_id = result[0]
        cur.execute("INSERT INTO internships (student_id, company_name, duration, feedback) VALUES (?, ?, ?, ?)",
                    (student_id, company, duration, feedback))
        conn.commit()
    conn.close()

def fetch_reports():
    conn = get_connection()
    cur = conn.cursor()
    cur.execute('''
    SELECT s.name, s.email, i.company_name, i.duration, i.feedback
    FROM students s
    JOIN internships i ON s.student_id = i.student_id
    ''')
    return cur.fetchall()

def generate_pdf_report(data):
    pdf_path = "internship_report.pdf"
    c = canvas.Canvas(pdf_path)
    c.setFont("Helvetica", 12)
    y = 800
    for row in data:
        text = f"Name: {row[0]}, Email: {row[1]}, Company: {row[2]}, Duration: {row[3]}, Feedback: {row[4]}"
        c.drawString(30, y, text)
        y -= 20
        if y < 40:
            c.showPage()
            y = 800
    c.save()
    return pdf_path

# --- Streamlit UI ---
st.title("🎓 Internship Tracking System")

menu = ["Register Student", "Log Internship", "Generate Report"]
choice = st.sidebar.selectbox("Menu", menu)

if choice == "Register Student":
    st.subheader("📝 Student Registration")
    name = st.text_input("Name")
    email = st.text_input("Email")
    if st.button("Register"):
        register_student(name, email)
        st.success("Student registered successfully.")

elif choice == "Log Internship":
    st.subheader("🛠️ Log Internship")
    email = st.text_input("Student Email")
    company = st.text_input("Company Name")
    duration = st.text_input("Duration (e.g. 3 months)")
    feedback = st.text_area("Feedback")
    if st.button("Submit Internship"):
        log_internship(email, company, duration, feedback)
        st.success("Internship logged successfully.")

elif choice == "Generate Report":
    st.subheader("📄 Generate Internship Report")
    data = fetch_reports()
    if st.button("Generate PDF"):
        pdf_path = generate_pdf_report(data)
        with open(pdf_path, "rb") as f:
            st.download_button(label="Download Report", data=f, file_name="internship_report.pdf")